# Generated by Django 5.2.1 on 2025-09-04 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(choices=[('grams', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('ltr', 'Liters'), ('pieces', 'Pieces'), ('unit', 'Unit')], default='unit', max_length=20)),
                ('current_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('safety_stock', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('eoq', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('bin_location', models.CharField(blank=True, max_length=100)),
                ('serialized', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('stock_turnover_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('forecast', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('ml_model_version', models.CharField(blank=True, max_length=50)),
                ('barcode_status', models.BooleanField(default=False)),
                ('rfid_tag_id', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurants.category')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurants.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('qty_before', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_after', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurants.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('uom', models.CharField(choices=[('grams', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('ltr', 'Liters'), ('pieces', 'Pieces'), ('unit', 'Unit')], default='unit', max_length=20)),
                ('transfer_order_number', models.CharField(blank=True, max_length=100)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('receive_date', models.DateField(blank=True, null=True)),
                ('batch_serial_number', models.CharField(blank=True, max_length=200)),
                ('inspection_status', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Restaurants.inventoryitem')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='Restaurants.warehouse')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='Restaurants.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
