# Generated by Django 5.2.1 on 2025-09-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisines',
            new_name='cuisine_id',
        ),
    ]
