# Generated by Django 5.2.1 on 2025-09-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_rename_cuisines_restaurant_cuisine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisine_id',
            new_name='cuisines',
        ),
    ]
