# Generated by Django 5.2.1 on 2025-09-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_supplier_warehouse_remove_stockhistory_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant_details',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='category',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurants.cuisine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurants.cuisine'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Restaurant_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_days', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('booking_allowed', models.BooleanField(default=False)),
                ('order_allowed', models.BooleanField(default=False)),
                ('last_booking_time', models.TimeField(blank=True, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='blocked_day',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='Restaurants.restaurant_schedule'),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant_schedule'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Restaurant_Details',
        ),
    ]
