# Generated by Django 5.2.1 on 2025-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_cuisine_remove_restaurant_details_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_configure',
            new_name='OrderConfigure',
        ),
        migrations.RenameModel(
            old_name='Restaurant_Schedule',
            new_name='RestaurantSchedule',
        ),
        migrations.RenameModel(
            old_name='resto_cover_img',
            new_name='RestoCoverImage',
        ),
        migrations.RenameModel(
            old_name='resto_gallery_img',
            new_name='RestoGalleryImage',
        ),
        migrations.RenameModel(
            old_name='resto_menu_img',
            new_name='RestoMenuImage',
        ),
        migrations.RenameModel(
            old_name='resto_otherfile',
            new_name='RestoOtherFile',
        ),
        migrations.RenameModel(
            old_name='Table_booking',
            new_name='TableBooking',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closing_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cost_for_two',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
