# Generated by Django 5.2.1 on 2025-09-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_rename_order_configure_orderconfigure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='Restaurants.restaurant'),
        ),
    ]
